### ISSUE TITLE
Can't see Apache logs when using docker-compose

### ISSUE THREAD

**Issue by vlatkorun** [fauria/docker-lap#6]
I can't see Apache logs. 

I have the following `docker-compose.yaml` file:

```
version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  phpmyadmin:
    driver: ${VOLUMES_DRIVER}

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
  web:
    image: fauria/lap
    environment:
      - LOG_STDOUT=${WEB_LOG_STDOUT}
      - LOG_STDERR=${WEB_LOG_STDERR}
      - LOG_LEVEL=${WEB_LOG_LEVEL}
      - ALLOW_OVERRIDE=${WEB_ALLOW_OVERRIDE}
      - DATE_TIMEZONE=${WEB_DATE_TIMEZONE}
    volumes:
      - ${WEB_LOG_PATH}:/var/log/httpd
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    ports:
      - "${WEB_HTTP_PORT}:80"
      - "${WEB_HTTPS_PORT}:443"
    networks:
      - frontend
      - backend
```

And the `.env` file:

```
### WEB/APACHE/PHP #################################################

WEB_LOG_STDOUT=true
WEB_LOG_STDERR=true
WEB_LOG_LEVEL=warn
WEB_ALLOW_OVERRIDE=All
WEB_DATE_TIMEZONE=Europe/Skopje
WEB_LOG_PATH=./logs/apache
WEB_HTTP_PORT=80
WEB_HTTPS_PORT=443
```

When `WEB_LOG_STDOUT=true` and `WEB_LOG_STDERR=true` running: `docker-compose logs -f -t web` doesn't show anything even if I throw an Exception from the index.php file.

If I set `WEB_LOG_STDOUT=false` and `WEB_LOG_STDERR=false` I still don't have any files into the  `/var/log/httpd` directory.

What can be the cause of it?
